#! python3
#pw.py - An insecure password locker program.

def manager(account):
    PASSWORDS = {'email' : ASHLEY456',
             'instagram' : 'AShley@123h',
             'facebook' : 'greatmib745'}

import sys, pyperclip

if len(sys.argv) <2:
    print('Usage: python pw.py [account] - copy account password')
    sys.exit()

if account in PASSWORDS:
    pyperclip.copy(PASSWORDS[account])
    print('Password ' + account + ' copied to clipboard.')
else:
    print('There is no account named ' + account)
if __name__="__main__":
    account = sys.argv[1] #first command line arg is the account name
    manager(account)
    


